# Generated by Django 3.2.8 on 2021-10-07 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='parent',
        ),
    ]
