# Generated by Django 3.2.8 on 2021-10-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('outwear', 'outwear'), ('shoes', 'shoes'), ('pants', 'pants'), ('accessories', 'accessories')], default='outwear', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
