# Generated by Django 3.2.8 on 2021-10-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211014_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=200, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Сообщения',
                'verbose_name_plural': 'Сообщении',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('pants', 'pants'), ('shoes', 'shoes'), ('accessories', 'accessories'), ('outwear', 'outwear')], default='outwear', max_length=20),
        ),
    ]
