# Generated by Django 3.2.8 on 2021-10-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20211018_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('outwear', 'outwear'), ('pants', 'pants'), ('shoes', 'shoes'), ('accessories', 'accessories')], default='outwear', max_length=20),
        ),
    ]
