# Generated by Django 3.2.8 on 2021-10-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211018_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='moderation',
            field=models.BooleanField(default=False, null=True, verbose_name='Модерация'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('accessories', 'accessories'), ('pants', 'pants'), ('shoes', 'shoes'), ('outwear', 'outwear')], default='outwear', max_length=20),
        ),
    ]
