# Generated by Django 3.2.8 on 2021-10-26 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20211026_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='сountry',
            new_name='country',
        ),
    ]
