# Generated by Django 3.2.8 on 2021-10-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_сountry_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('outwear', 'outwear'), ('accessories', 'accessories'), ('shoes', 'shoes'), ('pants', 'pants')], default='outwear', max_length=20),
        ),
    ]
