# Generated by Django 3.2.8 on 2021-10-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='lat_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='long_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('pants', 'pants'), ('shoes', 'shoes'), ('outwear', 'outwear'), ('accessories', 'accessories')], default='outwear', max_length=20),
        ),
    ]
