# Generated by Django 3.2.8 on 2021-10-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20211026_0426'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AddField(
            model_name='contact',
            name='behance',
            field=models.URLField(null=True, verbose_name='URl для behance странице'),
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(max_length=30, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(max_length=30, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='contact',
            name='facebook',
            field=models.URLField(null=True, verbose_name='URl для facebook странице'),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin',
            field=models.URLField(null=True, verbose_name='URl для linkedin странице'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=30, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='contact',
            name='street',
            field=models.CharField(max_length=30, null=True, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='contact',
            name='twitter',
            field=models.URLField(null=True, verbose_name='URl для twitter странице'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('shoes', 'shoes'), ('outwear', 'outwear'), ('pants', 'pants'), ('accessories', 'accessories')], default='outwear', max_length=20),
        ),
    ]
