# Generated by Django 3.2.8 on 2021-12-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20211026_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('pants', 'pants'), ('accessories', 'accessories'), ('shoes', 'shoes'), ('outwear', 'outwear')], default='outwear', max_length=20),
        ),
    ]
