# Generated by Django 4.0 on 2021-12-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('accessories', 'accessories'), ('pants', 'pants'), ('shoes', 'shoes'), ('outwear', 'outwear')], default='outwear', max_length=20),
        ),
    ]
